spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/demo
    driver-class-name: org.postgresql.Driver
  jooq: 
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
    
management:
  security:
    enabled: false